name: Update protos
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  
jobs:
  update-protos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1.15.0
      
      - name: Update
        run: |
          ./update_protos.sh
        
      - name: Commit
        run: |
          git config --global user.email "automated@example.com"
          git config --global user.name "Automated"
          git checkout -b scheduled
          git add .
          git commit -m "Scheduled Update"
          git push origin scheduled

      - name: Create pull request
        run: gh pr create -B scheduled -H master --title "Scheduled Update" --body "Update protos"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}